[build]
  command = "npm run build"
  publish = "site/public"
  ignore = "node ./scripts/netlify-ignore-build.cjs"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"

  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
