const assert = require('node:assert/strict')
const { test } = require('node:test')

const loadComments = () =>
  import('../../netlify/functions/_shared/comments.mts')

const env = {
  SUPABASE_URL: 'https://project.supabase.co',
  SUPABASE_SECRET_KEY: 'sb_secret_test',
  TURNSTILE_SECRET_KEY: 'turnstile-secret',
  RESEND_API_KEY: 'resend-secret',
  COMMENTS_OWNER_EMAIL: 'owner@example.com',
  COMMENTS_ADMIN_GITHUB_LOGIN: 'owner-login',
  COMMENTS_FROM_EMAIL: 'Owner <owner@example.com>',
  SITE_URL: 'https://example.com'
}

test('uses the deploy URL for links generated by a deploy preview', async () => {
  const { getEnvironment } = await loadComments()
  const original = {
    CONTEXT: process.env.CONTEXT,
    DEPLOY_PRIME_URL: process.env.DEPLOY_PRIME_URL,
    SITE_URL: process.env.SITE_URL
  }

  try {
    process.env.CONTEXT = 'deploy-preview'
    process.env.DEPLOY_PRIME_URL =
      'https://deploy-preview-42--uylas.netlify.app'
    process.env.SITE_URL = 'https://www.ibrahimuylas.com'

    assert.equal(
      getEnvironment().SITE_URL,
      'https://deploy-preview-42--uylas.netlify.app'
    )
  } finally {
    for (const [key, value] of Object.entries(original)) {
      if (value === undefined) delete process.env[key]
      else process.env[key] = value
    }
  }
})

test('normalizes article paths and validates a public submission', async () => {
  const { normalizePath, publicCommentPayload, sha256 } = await loadComments()

  assert.equal(normalizePath('/test-post?preview=true'), '/test-post/')
  assert.equal(normalizePath('https://example.com/test'), '')

  const prepared = publicCommentPayload(
    {
      path: '/test-post?preview=true',
      title: ' Test post ',
      name: ' Reader ',
      email: ' Reader@Example.com ',
      comment: ' First line\r\nSecond line ',
      notifyReplies: true,
      replyTo: 42
    },
    env
  )

  assert.ok(prepared)
  assert.equal(prepared.rpc.p_path, '/test-post/')
  assert.equal(prepared.rpc.p_email, 'reader@example.com')
  assert.equal(prepared.rpc.p_email_hash, sha256('reader@example.com'))
  assert.equal(prepared.rpc.p_body, 'First line\nSecond line')
  assert.equal(prepared.rpc.p_reply_to_id, 42)
  assert.equal(prepared.rpc.p_notify_replies, true)
  assert.notEqual(
    prepared.rpc.p_verification_token_hash,
    prepared.rpc.p_unsubscribe_token_hash
  )
})

test('rejects malformed or oversized public submissions', async () => {
  const { publicCommentPayload } = await loadComments()
  const base = {
    path: '/post/',
    title: 'Post',
    name: 'Reader',
    email: 'reader@example.com',
    comment: 'Hello'
  }

  assert.equal(publicCommentPayload({ ...base, email: 'invalid' }, env), null)
  assert.equal(
    publicCommentPayload({ ...base, comment: 'x'.repeat(5001) }, env),
    null
  )
  assert.equal(publicCommentPayload({ ...base, replyTo: -1 }, env), null)
})

test('uses the Supabase secret only in the server-side apikey header', async () => {
  const { supabaseRpc } = await loadComments()
  const calls = []
  const result = await supabaseRpc(
    env,
    'list_comments_internal',
    { p_path: '/post/' },
    async (url, options) => {
      calls.push({ url, options })
      return Response.json({ items: [], nextCursor: null })
    }
  )

  assert.deepEqual(result, { items: [], nextCursor: null })
  assert.equal(calls[0].options.headers.apikey, env.SUPABASE_SECRET_KEY)
  assert.equal(calls[0].options.headers.Authorization, undefined)
  assert.doesNotMatch(JSON.stringify(result), /sb_secret_test/)
})

test('verifies Turnstile with the secret and remote address', async () => {
  const { verifyTurnstile } = await loadComments()
  let request
  const ok = await verifyTurnstile(
    env,
    'browser-token',
    '203.0.113.4',
    async (url, options) => {
      request = { url, options }
      return Response.json({ success: true })
    }
  )

  assert.equal(ok, true)
  assert.match(request.url, /turnstile\/v0\/siteverify/)
  assert.equal(request.options.body.get('response'), 'browser-token')
  assert.equal(request.options.body.get('remoteip'), '203.0.113.4')
})

test('authorizes comment management with the existing Decap GitHub token', async () => {
  const { getAdminUser } = await loadComments()
  let request
  const user = await getAdminUser(
    new Request('https://example.com/api/comments/admin', {
      headers: { Authorization: 'Bearer github-oauth-token' }
    }),
    env,
    async (url, options) => {
      request = { url, options }
      return Response.json({ id: 42, login: 'owner-login', type: 'User' })
    }
  )

  assert.equal(request.url, 'https://api.github.com/user')
  assert.equal(
    request.options.headers.Authorization,
    'Bearer github-oauth-token'
  )
  assert.equal(request.options.headers['X-GitHub-Api-Version'], '2026-03-10')
  assert.equal(user.login, 'owner-login')
  assert.match(
    user.id,
    /^[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/
  )
})

test('rejects a valid GitHub token owned by a different account', async () => {
  const { getAdminUser } = await loadComments()
  const user = await getAdminUser(
    new Request('https://example.com/api/comments/admin', {
      headers: { Authorization: 'Bearer another-token' }
    }),
    env,
    async () => Response.json({ id: 7, login: 'someone-else', type: 'User' })
  )

  assert.equal(user, null)
})

test('allows the Decap local proxy token only in Netlify dev on localhost', async () => {
  const { getAdminUser } = await loadComments()
  const request = new Request('http://localhost:8888/api/comments/admin', {
    headers: { Authorization: 'Bearer decap-local' }
  })

  const localUser = await getAdminUser(request, { ...env, CONTEXT: 'dev' })
  const productionUser = await getAdminUser(
    request,
    { ...env, CONTEXT: 'production' },
    async () => new Response(null, { status: 401 })
  )

  assert.equal(localUser.login, 'local-development')
  assert.equal(productionUser, null)
})

test('sends claimed outbox mail with a stable Resend idempotency key', async () => {
  const { drainEmailOutbox } = await loadComments()
  const calls = []
  const fetchImpl = async (url, options) => {
    calls.push({ url, options })
    if (url.endsWith('/rpc/claim_comment_email_jobs_internal')) {
      return Response.json([
        {
          id: 7,
          kind: 'owner_new_comment',
          recipient: 'owner@example.com',
          idempotency_key: 'owner-new-comment:19',
          payload: {
            authorName: 'Reader',
            body: '<script>alert(1)</script>',
            path: '/post/',
            title: 'Post',
            commentId: 19
          }
        }
      ])
    }
    if (url === 'https://api.resend.com/emails') {
      return Response.json({ id: 'email-1' })
    }
    if (url.endsWith('/rpc/finish_comment_email_job_internal')) {
      return Response.json(null)
    }
    throw new Error(`Unexpected URL: ${url}`)
  }

  assert.equal(await drainEmailOutbox(env, fetchImpl), 1)
  const resend = calls.find(call => call.url.includes('api.resend.com'))
  assert.equal(
    resend.options.headers['Idempotency-Key'],
    'owner-new-comment:19'
  )
  const body = JSON.parse(resend.options.body)
  assert.doesNotMatch(body.html, /<script>/)
  assert.match(body.html, /&lt;script&gt;/)
  assert.match(body.html, /\/admin\/#\/comments-management\?comment=19/)
})

test('does not claim outbox work when email delivery is not configured', async () => {
  const { drainEmailOutbox } = await loadComments()
  let fetchCalled = false

  await assert.rejects(
    drainEmailOutbox({ ...env, RESEND_API_KEY: undefined }, async () => {
      fetchCalled = true
      return Response.json([])
    }),
    /RESEND_API_KEY/
  )

  assert.equal(fetchCalled, false)
})
