server {
    listen 3333;
    listen [::]:3333;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {
        try_files $uri $uri/ $uri.html /404.html;
    }

    location = /404.html {
        internal;
    }
}
