create table public.article_reaction_threads (
  id bigint generated by default as identity primary key,
  path text not null unique check (path ~ '^/.*' and length(path) <= 500),
  title text not null check (length(title) between 1 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.article_reaction_totals (
  thread_id bigint not null references public.article_reaction_threads(id) on delete cascade,
  reaction text not null check (
    reaction in ('like', 'funny', 'love', 'surprised', 'angry', 'sad')
  ),
  imported_count integer not null default 0 check (imported_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (thread_id, reaction)
);

create table public.article_reaction_votes (
  thread_id bigint not null references public.article_reaction_threads(id) on delete cascade,
  visitor_hash text not null check (visitor_hash ~ '^[0-9a-f]{64}$'),
  reaction text not null check (
    reaction in ('like', 'funny', 'love', 'surprised', 'angry', 'sad')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (thread_id, visitor_hash)
);

alter table public.article_reaction_threads enable row level security;
alter table public.article_reaction_totals enable row level security;
alter table public.article_reaction_votes enable row level security;

revoke all on table public.article_reaction_threads from public, anon, authenticated;
revoke all on table public.article_reaction_totals from public, anon, authenticated;
revoke all on table public.article_reaction_votes from public, anon, authenticated;

grant select, insert, update on table public.article_reaction_threads to service_role;
grant select, insert, update on table public.article_reaction_totals to service_role;
grant select, insert, update, delete on table public.article_reaction_votes to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.list_article_reactions_internal(
  p_path text,
  p_visitor_hash text default null
) returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  with requested_thread as (
    select id
    from public.article_reaction_threads
    where path = p_path
  ), reaction_options(reaction, position) as (
    values
      ('like'::text, 1),
      ('funny'::text, 2),
      ('love'::text, 3),
      ('surprised'::text, 4),
      ('angry'::text, 5),
      ('sad'::text, 6)
  ), native_votes as (
    select v.reaction, count(*)::integer as vote_count
    from public.article_reaction_votes v
    join requested_thread t on t.id = v.thread_id
    group by v.reaction
  )
  select jsonb_build_object(
    'items', jsonb_agg(
      jsonb_build_object(
        'reaction', options.reaction,
        'count', coalesce(totals.imported_count, 0) + coalesce(native_votes.vote_count, 0)
      ) order by options.position
    ),
    'selected', (
      select votes.reaction
      from public.article_reaction_votes votes
      join requested_thread thread on thread.id = votes.thread_id
      where p_visitor_hash is not null
        and votes.visitor_hash = p_visitor_hash
      limit 1
    )
  )
  from reaction_options options
  left join requested_thread thread on true
  left join public.article_reaction_totals totals
    on totals.thread_id = thread.id and totals.reaction = options.reaction
  left join native_votes on native_votes.reaction = options.reaction;
$$;

create or replace function public.toggle_article_reaction_internal(
  p_path text,
  p_title text,
  p_reaction text,
  p_visitor_hash text
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_thread public.article_reaction_threads;
  v_existing_reaction text;
begin
  if coalesce(p_path !~ '^/.*' or length(p_path) > 500, true)
    or coalesce(length(trim(p_title)) not between 1 and 300, true)
    or coalesce(
      p_reaction not in ('like', 'funny', 'love', 'surprised', 'angry', 'sad'),
      true
    )
    or coalesce(p_visitor_hash !~ '^[0-9a-f]{64}$', true)
  then
    raise exception 'invalid reaction input' using errcode = '22023';
  end if;

  insert into public.article_reaction_threads(path, title)
  values (p_path, trim(p_title))
  on conflict (path) do update set
    title = excluded.title,
    updated_at = now()
  returning * into v_thread;

  select reaction into v_existing_reaction
  from public.article_reaction_votes
  where thread_id = v_thread.id and visitor_hash = p_visitor_hash
  for update;

  if found and v_existing_reaction = p_reaction then
    delete from public.article_reaction_votes
    where thread_id = v_thread.id and visitor_hash = p_visitor_hash;
  else
    insert into public.article_reaction_votes(
      thread_id, visitor_hash, reaction
    ) values (
      v_thread.id, p_visitor_hash, p_reaction
    )
    on conflict (thread_id, visitor_hash) do update set
      reaction = excluded.reaction,
      updated_at = now();
  end if;

  return public.list_article_reactions_internal(p_path, p_visitor_hash);
end;
$$;

revoke all on function public.list_article_reactions_internal(text,text)
  from public, anon, authenticated;
revoke all on function public.toggle_article_reaction_internal(text,text,text,text)
  from public, anon, authenticated;

grant execute on function public.list_article_reactions_internal(text,text)
  to service_role;
grant execute on function public.toggle_article_reaction_internal(text,text,text,text)
  to service_role;
