create extension if not exists pgcrypto with schema extensions;

create table public.comment_threads (
  id bigint generated by default as identity primary key,
  path text not null unique check (path ~ '^/.*' and length(path) <= 500),
  title text not null check (length(title) between 1 and 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.comments (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.comment_threads(id) on delete restrict,
  root_comment_id bigint references public.comments(id) on delete restrict,
  reply_to_comment_id bigint references public.comments(id) on delete restrict,
  author_name text not null check (length(author_name) between 1 and 80),
  body text not null check (length(body) between 1 and 5000),
  status text not null default 'published' check (status in ('published', 'hidden')),
  source text not null default 'native' check (source in ('native', 'disqus')),
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  edited_at timestamptz,
  hidden_at timestamptz,
  last_activity_at timestamptz not null default now(),
  check (
    (root_comment_id is null and reply_to_comment_id is null) or
    (root_comment_id is not null and reply_to_comment_id is not null)
  )
);

create unique index comments_source_id_key
  on public.comments(source, source_id) where source_id is not null;
create index comments_thread_roots_idx
  on public.comments(thread_id, last_activity_at desc, id desc)
  where root_comment_id is null;
create index comments_root_replies_idx
  on public.comments(root_comment_id, created_at, id)
  where root_comment_id is not null;
create index comments_reply_target_idx on public.comments(reply_to_comment_id);

create table public.comment_contacts (
  comment_id bigint primary key references public.comments(id) on delete cascade,
  email text not null check (length(email) between 3 and 254),
  normalized_email_hash text not null,
  notify_replies boolean not null default false,
  email_verified_at timestamptz,
  verification_token_hash text,
  verification_expires_at timestamptz,
  unsubscribe_token_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index comment_contacts_email_hash_idx
  on public.comment_contacts(normalized_email_hash);
create unique index comment_contacts_verification_token_key
  on public.comment_contacts(verification_token_hash)
  where verification_token_hash is not null;
create unique index comment_contacts_unsubscribe_token_key
  on public.comment_contacts(unsubscribe_token_hash);

create table public.comment_email_outbox (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('owner_new_comment', 'verify_email', 'direct_reply')),
  comment_id bigint references public.comments(id) on delete cascade,
  recipient text not null check (length(recipient) between 3 and 254),
  payload jsonb not null default '{}'::jsonb,
  state text not null default 'pending' check (state in ('pending', 'sending', 'sent', 'failed')),
  attempt_count smallint not null default 0 check (attempt_count between 0 and 8),
  next_attempt_at timestamptz not null default now(),
  first_attempt_at timestamptz,
  provider_id text,
  last_error text,
  idempotency_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index comment_email_outbox_due_idx
  on public.comment_email_outbox(next_attempt_at, id)
  where state in ('pending', 'failed') and attempt_count < 8;

create table public.comment_moderation_events (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete restrict,
  admin_user_id uuid not null,
  action text not null check (action in ('hide', 'restore', 'edit', 'reply')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index comment_moderation_events_comment_idx
  on public.comment_moderation_events(comment_id, created_at desc);

alter table public.comment_threads enable row level security;
alter table public.comments enable row level security;
alter table public.comment_contacts enable row level security;
alter table public.comment_email_outbox enable row level security;
alter table public.comment_moderation_events enable row level security;

revoke all on table public.comment_threads from public, anon, authenticated;
revoke all on table public.comments from public, anon, authenticated;
revoke all on table public.comment_contacts from public, anon, authenticated;
revoke all on table public.comment_email_outbox from public, anon, authenticated;
revoke all on table public.comment_moderation_events from public, anon, authenticated;
revoke all on all sequences in schema public from public, anon, authenticated;

grant select, insert, update on table public.comment_threads to service_role;
grant select, insert, update on table public.comments to service_role;
grant select, insert, update on table public.comment_contacts to service_role;
grant select, insert, update on table public.comment_email_outbox to service_role;
grant select, insert on table public.comment_moderation_events to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.submit_comment_internal(
  p_path text,
  p_title text,
  p_author_name text,
  p_email text,
  p_email_hash text,
  p_body text,
  p_reply_to_id bigint,
  p_notify_replies boolean,
  p_verification_token_hash text,
  p_verification_expires_at timestamptz,
  p_unsubscribe_token_hash text,
  p_owner_email text,
  p_email_payload jsonb,
  p_is_admin boolean default false,
  p_admin_user_id uuid default null
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_thread public.comment_threads;
  v_parent public.comments;
  v_root_id bigint;
  v_comment public.comments;
  v_parent_contact public.comment_contacts;
  v_parent_unsubscribe_token text;
begin
  insert into public.comment_threads(path, title)
  values (p_path, p_title)
  on conflict (path) do update set
    title = excluded.title,
    updated_at = now()
  returning * into v_thread;

  if p_reply_to_id is not null then
    select * into v_parent
    from public.comments
    where id = p_reply_to_id and thread_id = v_thread.id and status = 'published';

    if not found then
      raise exception 'reply target not found' using errcode = '22023';
    end if;

    v_root_id := coalesce(v_parent.root_comment_id, v_parent.id);
  end if;

  insert into public.comments(
    thread_id, root_comment_id, reply_to_comment_id, author_name, body
  ) values (
    v_thread.id, v_root_id, p_reply_to_id, p_author_name, p_body
  ) returning * into v_comment;

  if v_root_id is not null then
    update public.comments
    set last_activity_at = v_comment.created_at, updated_at = now()
    where id = v_root_id;
  end if;

  insert into public.comment_contacts(
    comment_id, email, normalized_email_hash, notify_replies,
    email_verified_at, verification_token_hash, verification_expires_at,
    unsubscribe_token_hash
  ) values (
    v_comment.id, p_email, p_email_hash, p_notify_replies,
    case when p_is_admin then now() else null end,
    case when p_notify_replies and not p_is_admin then p_verification_token_hash else null end,
    case when p_notify_replies and not p_is_admin then p_verification_expires_at else null end,
    p_unsubscribe_token_hash
  );

  if not p_is_admin then
    insert into public.comment_email_outbox(
      kind, comment_id, recipient, payload, idempotency_key
    ) values (
      'owner_new_comment', v_comment.id, p_owner_email,
      p_email_payload || jsonb_build_object('commentId', v_comment.id),
      'owner-new-comment:' || v_comment.id
    );
  end if;

  if p_notify_replies and not p_is_admin then
    insert into public.comment_email_outbox(
      kind, comment_id, recipient, payload, idempotency_key
    ) values (
      'verify_email', v_comment.id, p_email,
      p_email_payload || jsonb_build_object('commentId', v_comment.id),
      'verify-email:' || v_comment.id
    );
  end if;

  if p_reply_to_id is not null then
    select * into v_parent_contact
    from public.comment_contacts
    where comment_id = p_reply_to_id
      and notify_replies = true
      and email_verified_at is not null
      and normalized_email_hash <> p_email_hash;

    if found then
      select payload ->> 'unsubscribeToken' into v_parent_unsubscribe_token
      from public.comment_email_outbox
      where comment_id = p_reply_to_id and kind = 'verify_email'
      order by id desc limit 1;

      insert into public.comment_email_outbox(
        kind, comment_id, recipient, payload, idempotency_key
      ) values (
        'direct_reply', v_comment.id, v_parent_contact.email,
        p_email_payload || jsonb_build_object(
          'commentId', v_comment.id,
          'unsubscribeToken', v_parent_unsubscribe_token
        ),
        'direct-reply:' || v_comment.id || ':' || p_reply_to_id
      );
    end if;
  end if;

  if p_is_admin and p_admin_user_id is not null and p_reply_to_id is not null then
    insert into public.comment_moderation_events(comment_id, admin_user_id, action, details)
    values (v_comment.id, p_admin_user_id, 'reply', jsonb_build_object('reply_to', p_reply_to_id));
  end if;

  return jsonb_build_object(
    'id', v_comment.id,
    'authorName', v_comment.author_name,
    'body', v_comment.body,
    'createdAt', v_comment.created_at,
    'rootCommentId', v_comment.root_comment_id,
    'replyToCommentId', v_comment.reply_to_comment_id
  );
end;
$$;

create or replace function public.list_comments_internal(
  p_path text,
  p_sort text default 'newest',
  p_cursor timestamptz default null,
  p_limit integer default 20
) returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  with thread as (
    select id from public.comment_threads where path = p_path
  ), roots as (
    select c.*
    from public.comments c
    join thread t on t.id = c.thread_id
    where c.root_comment_id is null
      and (p_cursor is null or
        (p_sort = 'oldest' and c.last_activity_at > p_cursor) or
        (p_sort <> 'oldest' and c.last_activity_at < p_cursor))
    order by
      case when p_sort = 'oldest' then c.last_activity_at end asc,
      case when p_sort <> 'oldest' then c.last_activity_at end desc,
      c.id desc
    limit least(greatest(p_limit, 1), 20) + 1
  ), page as (
    select * from roots
    order by
      case when p_sort = 'oldest' then last_activity_at end asc,
      case when p_sort <> 'oldest' then last_activity_at end desc,
      id desc
    limit least(greatest(p_limit, 1), 20)
  ), items as (
    select jsonb_build_object(
      'id', r.id,
      'authorName', case when r.status = 'hidden' then null else r.author_name end,
      'body', case when r.status = 'hidden' then null else r.body end,
      'status', r.status,
      'createdAt', r.created_at,
      'editedAt', r.edited_at,
      'replies', coalesce((
        select jsonb_agg(jsonb_build_object(
          'id', q.id,
          'authorName', q.author_name,
          'body', q.body,
          'status', q.status,
          'createdAt', q.created_at,
          'editedAt', q.edited_at,
          'replyToCommentId', q.reply_to_comment_id
        ) order by q.created_at, q.id)
        from public.comments q
        where q.root_comment_id = r.id and q.status = 'published'
      ), '[]'::jsonb)
    ) as item, r.last_activity_at
    from page r
  )
  select jsonb_build_object(
    'items', coalesce((select jsonb_agg(item order by
      case when p_sort = 'oldest' then last_activity_at end asc,
      case when p_sort <> 'oldest' then last_activity_at end desc
    ) from items), '[]'::jsonb),
    'nextCursor', case when (select count(*) from roots) > least(greatest(p_limit, 1), 20)
      then (select last_activity_at from page order by
        case when p_sort = 'oldest' then last_activity_at end desc,
        case when p_sort <> 'oldest' then last_activity_at end asc
        limit 1)
      else null end
  );
$$;

create or replace function public.verify_comment_email_internal(p_token_hash text)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.comment_contacts
  set email_verified_at = now(), verification_token_hash = null,
      verification_expires_at = null, updated_at = now()
  where verification_token_hash = p_token_hash
    and verification_expires_at > now();
  return found;
end;
$$;

create or replace function public.unsubscribe_comment_email_internal(p_token_hash text)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.comment_contacts
  set notify_replies = false, verification_token_hash = null,
      verification_expires_at = null, updated_at = now()
  where unsubscribe_token_hash = p_token_hash;
  return found;
end;
$$;

create or replace function public.moderate_comment_internal(
  p_comment_id bigint,
  p_action text,
  p_body text,
  p_admin_user_id uuid
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare v_old_body text;
begin
  select body into v_old_body from public.comments where id = p_comment_id for update;
  if not found then return false; end if;

  if p_action = 'hide' then
    update public.comments set status = 'hidden', hidden_at = now(), updated_at = now()
    where id = p_comment_id;
  elsif p_action = 'restore' then
    update public.comments set status = 'published', hidden_at = null, updated_at = now()
    where id = p_comment_id;
  elsif p_action = 'edit' and length(trim(p_body)) between 1 and 5000 then
    update public.comments set body = trim(p_body), edited_at = now(), updated_at = now()
    where id = p_comment_id;
  else
    raise exception 'invalid moderation action' using errcode = '22023';
  end if;

  insert into public.comment_moderation_events(comment_id, admin_user_id, action, details)
  values (p_comment_id, p_admin_user_id, p_action,
    case when p_action = 'edit' then jsonb_build_object('previousBody', v_old_body) else '{}'::jsonb end);
  return true;
end;
$$;

create or replace function public.list_comments_admin_internal(p_limit integer default 100)
returns table (
  id bigint, path text, title text, author_name text, email text, body text,
  status text, created_at timestamptz, root_comment_id bigint,
  reply_to_comment_id bigint, notify_replies boolean, email_verified boolean
)
language sql
stable
security invoker
set search_path = ''
as $$
  select c.id, t.path, t.title, c.author_name, cc.email, c.body, c.status,
    c.created_at, c.root_comment_id, c.reply_to_comment_id,
    cc.notify_replies, cc.email_verified_at is not null
  from public.comments c
  join public.comment_threads t on t.id = c.thread_id
  join public.comment_contacts cc on cc.comment_id = c.id
  order by c.created_at desc
  limit least(greatest(p_limit, 1), 200);
$$;

create or replace function public.claim_comment_email_jobs_internal(p_limit integer default 20)
returns setof public.comment_email_outbox
language plpgsql
security invoker
set search_path = ''
as $$
begin
  return query
  with due as (
    select id from public.comment_email_outbox
    where state in ('pending', 'failed')
      and attempt_count < 8
      and next_attempt_at <= now()
      and created_at > now() - interval '24 hours'
    order by next_attempt_at, id
    for update skip locked
    limit least(greatest(p_limit, 1), 50)
  )
  update public.comment_email_outbox o
  set state = 'sending', attempt_count = attempt_count + 1,
      first_attempt_at = coalesce(first_attempt_at, now()), updated_at = now()
  from due where o.id = due.id
  returning o.*;
end;
$$;

create or replace function public.finish_comment_email_job_internal(
  p_id bigint,
  p_sent boolean,
  p_provider_id text default null,
  p_error text default null
) returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.comment_email_outbox
  set state = case when p_sent then 'sent' else 'failed' end,
      provider_id = case when p_sent then p_provider_id else provider_id end,
      last_error = case when p_sent then null else left(coalesce(p_error, 'delivery failed'), 500) end,
      next_attempt_at = case when p_sent then next_attempt_at
        else now() + make_interval(mins => least(720, (15 * power(2, greatest(attempt_count - 1, 0)))::integer)) end,
      updated_at = now()
  where id = p_id and state = 'sending';
end;
$$;

revoke all on function public.submit_comment_internal(text,text,text,text,text,text,bigint,boolean,text,timestamptz,text,text,jsonb,boolean,uuid) from public, anon, authenticated;
revoke all on function public.list_comments_internal(text,text,timestamptz,integer) from public, anon, authenticated;
revoke all on function public.verify_comment_email_internal(text) from public, anon, authenticated;
revoke all on function public.unsubscribe_comment_email_internal(text) from public, anon, authenticated;
revoke all on function public.moderate_comment_internal(bigint,text,text,uuid) from public, anon, authenticated;
revoke all on function public.list_comments_admin_internal(integer) from public, anon, authenticated;
revoke all on function public.claim_comment_email_jobs_internal(integer) from public, anon, authenticated;
revoke all on function public.finish_comment_email_job_internal(bigint,boolean,text,text) from public, anon, authenticated;

grant execute on function public.submit_comment_internal(text,text,text,text,text,text,bigint,boolean,text,timestamptz,text,text,jsonb,boolean,uuid) to service_role;
grant execute on function public.list_comments_internal(text,text,timestamptz,integer) to service_role;
grant execute on function public.verify_comment_email_internal(text) to service_role;
grant execute on function public.unsubscribe_comment_email_internal(text) to service_role;
grant execute on function public.moderate_comment_internal(bigint,text,text,uuid) to service_role;
grant execute on function public.list_comments_admin_internal(integer) to service_role;
grant execute on function public.claim_comment_email_jobs_internal(integer) to service_role;
grant execute on function public.finish_comment_email_job_internal(bigint,boolean,text,text) to service_role;
